stages:
    - build_and_test

test_kaic:
    stage: build_and_test
    before_script:
        - "echo 'backend: Agg' > matplotlibrc"
        - "virtualenv kaic_venv"
        - "source kaic_venv/bin/activate"
        - "pip install --upgrade pip setuptools"
        - "mkdir dependencies"
        - "cd dependencies"
        - "git clone git@10.84.50.12:kkruse/genomic-regions.git"
        - "pip install ./genomic-regions/"
        - "cd .."
        - "rm -rf ./dependencies"
        - "pip install ."
    script:
        - "py.test kaic -m 'not plotting'"
    tags:
        - linux

test_plotting:
    stage: build_and_test
    before_script:
        - "echo 'backend: Agg' > matplotlibrc"
        - "virtualenv kaic_venv"
        - "source kaic_venv/bin/activate"
        - "pip install --upgrade pip setuptools"
        - "mkdir dependencies"
        - "cd dependencies"
        - "git clone git@10.84.50.12:kkruse/genomic-regions.git"
        - "pip install ./genomic-regions/"
        - "cd .."
        - "rm -rf ./dependencies"
        - "pip install ."
    script:
        - "py.test kaic -m plotting"
    tags:
        - linux

test_doc:
    stage: build_and_test
    before_script:
        - "virtualenv kaic_doc_venv"
        - "source kaic_doc_venv/bin/activate"
        - "pip install --upgrade pip setuptools"
        - "mkdir dependencies"
        - "cd dependencies"
        - "git clone git@10.84.50.12:kkruse/genomic-regions.git"
        - "pip install ./genomic-regions/"
        - "cd .."
        - "rm -rf ./dependencies"
        - "pip install sphinx sphinx-argparse sphinx_rtd_theme"
        - "pip install ."
    script:
        - cd kaic-doc
        - make html
        - cp -r _build/html/ /home/kkruse/kaic-doc
    tags:
        - linux
