before_script:
    - "virtualenv kaic_venv"
    - "source kaic_venv/bin/activate"
    - "echo 'backend: Agg' > matplotlibrc"

stages:
    - build
    - test

job_build_linux:
    stage: build
    script:
        - "pip install cython"
        - "pip install --process-dependency-links .[plotting]"
    cache:
        paths:
            - kaic_venv/
    tags:
        - linux

job_test_kaic:
    stage: test
    script:
        - "py.test kaic -m 'not plotting'"
    cache:
        paths:
            - kaic_venv/
    tags:
        - linux
        - kaic_test

job_test_kaic_plotting:
    stage: test
    script:
        - "py.test kaic -m plotting"
    cache:
        paths:
            - kaic_venv/
    tags:
        - linux
        - plotting_test

job_test_build:
    stage: test
    script:
        - "pip install cython"
        - "pip install --process-dependency-links .[plotting]"
    tags:
        - linux
        - build_test
