before_script:
    - "virtualenv kaic_venv"
    - "source kaic_venv/bin/activate"
    - "pip install cython"

stages:
    - build_and_test

job_build_test_kaic:
    stage: build_and_test
    script:
        - "pip install --process-dependency-links ."
        - "py.test kaic -m 'not plotting'"
    tags:
        - linux

job_build_test_kaic_plotting:
    stage: build_and_test
    script:
        - "pip install --process-dependency-links .[plotting]"
        - "py.test kaic -m plotting"
    tags:
        - linux
