before_script:
    - "echo 'backend: Agg' > matplotlibrc"
    - "virtualenv kaic_venv"
    - "source kaic_venv/bin/activate"
    - "pip install --upgrade pip setuptools"
    - "pip install cython"
    - "pip install ."

stages:
    - build_and_test

test_kaic:
    stage: build_and_test
    script:
        - "py.test kaic -m 'not plotting'"
    tags:
        - linux

test_plotting:
    stage: build_and_test
    script:
        - "py.test kaic -m plotting"
    tags:
        - linux

test_doc:
    stage: build_and_test
    script:
        - pip install sphinx sphinx-argparse
        - cd kaic-doc
        - make html
        - cp -r _build/html/* /var/www/kaic/
    tags:
        - linux
