before_script:
    - "virtualenv kaic_venv"
    - "source kaic_venv/bin/activate"

stages:
    - build
    - test

job_build_linux:
    stage: build
    script:
        - "pip install cython"
        - "pip install --process-dependency-links .[plotting]"
    tags:
        - linux

job_test_kaic:
    stage: test
    script:
        - "py.test kaic -m 'not plotting'"
    tags:
        - linux

job_test_kaic_plotting:
    stage: test
    script:
        - "py.test kaic -m plotting"
    tags:
        - linux
