stages:
    - build_and_test

test_kaic:
    stage: build_and_test
    before_script:
        - "echo 'backend: Agg' > matplotlibrc"
        - "virtualenv kaic_venv"
        - "source kaic_venv/bin/activate"
        - "pip install ."
    script:
        - "py.test kaic -m 'not plotting'"
    tags:
        - linux

test_plotting:
    stage: build_and_test
    before_script:
        - "echo 'backend: Agg' > matplotlibrc"
        - "virtualenv kaic_venv"
        - "source kaic_venv/bin/activate"
        - "pip install ."
    script:
        - "py.test kaic -m plotting"
    tags:
        - linux

test_doc:
    stage: build_and_test
    script:
        - pip install sphinx sphinx-argparse
        - cd kaic-doc
        - make html
        - whoami
        - cp -r _build/html/ /home/kkruse/kaic-doc
    tags:
        - linux
