before_script:
    - "virtualenv kaic_venv"
    - "source kaic_venv/bin/activate"
    - "echo 'backend: Agg' > matplotlibrc"
    - "pip install --upgrade pip setuptools"

stages:
    - build_and_test

job_test_kaic:
    stage: build_and_test
    script:
        - "pip install cython"
        - "pip install ."
        - "py.test kaic -m 'not plotting'"
    tags:
        - linux

job_test_kaic_plotting:
    stage: build_and_test
    script:
        - "pip install cython"
        - "pip install ."
        - "py.test kaic -m plotting"
    tags:
        - linux

job_test_doc_generation:
    stage: build_and_test
    script:
        - "pip install cython"
        - "pip install ."
        - "pip install sphinx sphinx-argparse"
        - "cd kaic-doc"
        - "make html"
    tags:
        - linux
